trigger:
  branches:
    include:
    - staging/ci-kuiper2.0

pr:
  branches:
    include:
    - staging/ci-kuiper2.0


variables:
- group: kuiper2.0_group_variables
  - name: branch
    value: $[replace(variables['System.PullRequest.TargetBranchName'], 'refs/heads/', '')]
- ${{ else }}:
  - name: branch
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
jobs:
- job: Kuiper_basic
  strategy:
    matrix:
      ${{if true }}:
        'Kuiper2.0 32bit basic':
          group_var: 'KUIPER_BASIC_32_'
          artifact_name: 'kuiper_volume_basic_32'
        'Kuiper2.0 64bit basic':
          group_var: 'KUIPER_BASIC_64_'
          artifact_name: 'kuiper_volume_basic_64'
      ${{ if ne(variables['Build.Reason'], 'PullRequest')}}:
        'Kuiper2.0 32bit full':
          group_var: 'KUIPER_FULL_32_'
          artifact_name: 'kuiper_volume_full_32'
        'Kuiper2.0 64bit full':
          group_var: 'KUIPER_FULL_64_'
          artifact_name: 'kuiper_volume_full_64'
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      # sudo apt-get install -y qemu-user-static
      branch_name=$(echo $(branch) | tr 'a-z' 'A-Z' | sed 's/[^[:alnum:]]/_/g')
      var_name="$(group_var)$branch_name"
      ci/modify_config.sh ./config ${!var_name}
      # sudo bash build-docker.sh
      echo $var_name
      echo ${!var_name}
      ci/modify_config.sh ./config "${!var_name}"
      mkdir kuiper-volume
    displayName: 'Build image'
  - task: PublishPipelineArtifact@1
    condition: true
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/kuiper-volume'
      artifact: $(artifact_name)
      publishLocation: 'pipeline'