name: Kuiper2.0
on:
  push:
    branches:
      - staging/ci-kuiper2.0
  pull_request:
    branches:
      - staging/ci-kuiper2.0
env:
 BRANCH: ${{ github.head_ref || github.ref_name }} 

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32]
        build_type: [basic]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set env variabiles
        run: |
          echo $BRANCH
          branch_name=$(echo $BRANCH | tr 'a-z' 'A-Z' | sed 's/[^[:alnum:]]/_/g')
          type=$( echo ${{ matrix.build_type }} | tr 'a-z' 'A-Z')
          echo ARTIFACT_NAME=kuiper_"${{ matrix.build_type }}"_"${{ matrix.arch }}" >> $GITHUB_ENV
          echo BRANCH_NAME="$branch_name"_"$type"_"${{ matrix.arch }}" >> $GITHUB_ENV
      - name: Build image
        run: |
          ls -al /dev/sda*
          ci/modify_config.sh ./config "${{ vars[format('{0}', env.BRANCH_NAME )] }}"
          docker version
          docker run --rm -t --privileged aandrisa/kuiper2_multiplatform:latest /bin/bash -c "ls /home/"
      - name: Upload image
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/kuiper-volume
