name: Kuiper2.0
on:
  push:
    branches:
      - staging/ci-kuiper2.0
  pull_request:
    branches:
      - staging/ci-kuiper2.0
env:
 BRANCH: ${{ github.head_ref || github.ref_name }} 

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: {{ env.BRANCH }}
    strategy:
      matrix:
        arch: [32, 64]
        build_type: [basic, full]
        exclude:
          - build_type: ${{ github.event_name == 'push' && 'full' }}
      fail-fast: false
    steps:
      - run: |
          echo "Test pipeline"
          echo ${{ vars.TEST_VAR }}
          echo $BRANCH
