name: Kuiper2.0
on:
  push:
    branches:
      - staging/ci-kuiper2.0
  pull_request:
    branches:
      - staging/ci-kuiper2.0
env:
 BRANCH: ${{ github.head_ref || github.ref_name }} 

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32, 64]
        build_type: [basic, full]
        exclude:
          - build_type: ${{ github.event_name == 'push' && 'full' }}
      fail-fast: false
    steps:
      - name: Set env variabiles
        run: |
          branch_name=$(echo $BRANCH | tr 'a-z' 'A-Z' | sed 's/[^[:alnum:]]/_/g')
          type=$( echo ${{ matrix.build_type }} | tr 'a-z' 'A-Z')
          echo BRANCH_NAME="$branch_name"_"$type" >> $GITHUB_ENV
      - name: Build image
        run: |
          echo "Test pipeline"
          echo ${{ env.BRANCH_NAME }}
          echo ${{ vars[format('{0}', env.BRANCH_NAME )] }}
          echo ${{ vars.TEST_VAR1}}
        
