name: Kuiper2.0
on:
  push:
    branches:
      - staging/ci-kuiper2.0
  pull_request:
    branches:
      - staging/ci-kuiper2.0

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [32, 64]
        build_type: [basic, full]
      fail-fast: false
    if: ${{ github.event_name == 'pull_request' && matrix.build_type == 'full' }}
    steps:
      - run: echo "Test pipeline"
